[[remotes]]
name = "flathub"
url = "https://dl.flathub.org/repo/flathub.flatpakrepo"

[[packages]]
remote = "flathub"
app_id = "com.usebottles.bottles"

[[packages]]
remote = "flathub"
app_id = "com.github.tchx84.Flatseal"

[[packages]]
remote = "flathub"
app_id = "com.protonvpn.www"

[[packages]]
remote = "flathub"
app_id = "org.signal.Signal"

[[packages]]
remote = "flathub"
app_id = "com.vivaldi.Vivaldi"

[[packages]]
remote = "flathub"
app_id = "com.vscodium.codium"

[[packages]]
remote = "flathub"
app_id = "org.mozilla.firefox"

[[packages]]
remote = "flathub"
app_id = "me.proton.Pass"

[[packages]]
remote = "flathub"
app_id = "org.raspberrypi.rpi-imager"

[[packages]]
remote = "flathub"
app_id = "io.github.nokse22.asciidraw"

[[packages]]
remote = "flathub"
app_id = "org.videolan.VLC"

[[packages]]
remote = "flathub"
app_id = "com.mattjakeman.ExtensionManager"

[[packages]]
remote = "flathub"
app_id = "it.mijorus.gearlever"

[[packages]]
remote = "flathub"
app_id = "net.cozic.joplin_desktop"

[[packages]]
remote = "flathub"
app_id = "org.wireshark.Wireshark"

[[packages]]
remote = "flathub"
app_id = "io.github.pwr_solaar.solaar"

[[packages]]
remote = "flathub"
app_id = "org.localsend.localsend_app"

[[packages]]
remote = "flathub"
app_id = "org.gnome.font-viewer"

[[packages]]
remote = "flathub"
app_id = "org.gnome.Calculator"

[[packages]]
remote = "flathub"
app_id = "org.gnome.Extensions"   