name: Build bootc ISO

on:
  workflow_dispatch:

jobs:

  pre-cleanup:
    name: Clean workspace before build
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf ${{ runner.workspace }}/${{ github.event.repository.name }}/*
          
  build:
    runs-on: self-hosted
    name: Build bootc ISO and deloy as GitHub Release
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build iso with bootc Image Builder
        run: |
          mkdir -p output
          sudo podman run \
            --rm \
            --privileged \
            --security-opt label=type:unconfined_t \
            -v ${{ github.workspace }}/config.toml:/config.toml:ro \
            -v ${{ github.workspace }}/output:/output \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type anaconda-iso \
            ghcr.io/${{ github.repository }}:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bootc-$(date +%Y%m%d)-${{ github.sha }}.iso
          path: output/bootiso/install.iso
          retention-days: 5

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: output/bootiso/install.iso
          draft: true
          prerelease: true
          
